name: NPM Test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build kafka stack
        run: ./kafka-setup/start.sh
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: Install, Test
        run: |
          yarn install --frozen-lockfile
          yarn run test
        env:
          CI: true